version: "2"
networks:
  working:
services:
  jsreport:
    image: jsreport/jsreport:latest
    environment:
      - appPath=/templates
      - authentication:enabled=true
      - authentication:admin:password=zdkei29djk5F20sk5kd0w
    volumes:
      - ./data/jsreport:/jsreport
    ports:
      - 5488:5488
    networks:
      - working
  editor:
    image: node:alpine
    working_dir: /editor
    volumes:
      - ./editor:/editor
    networks:
      - working
    command: npm run dev
    ports:
      - 8080:8080
  api:
    build: ./api
    volumes:
      - ./api:/api
    working_dir: /api
    command: python -u run.py
    networks:
      - working
#  app:
#    build: ./app
#    volumes:
#      - ./app:/app
#    working_dir: /app
#    command: node run.js
#    depends_on:
#      - api
#    networks:
#      - working
#    ports:
#      - 8080:8080
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    networks:
      - working

